export const homeCardsData = [
    {
      card: "one",
      title: "Physical Assets",
      bgColor: "#c7bcdd",
      name: "Crowsfunded & Tokenization Assets",
      subName: "Recent Transactions",
      tableTitleOne: "Name",
      tableTitleTwo: "Price",
      tableTitleThree: "Chanee",
      tableData: [
        {
          tableId: "1a",
          tableBodyTitle: "SmartCrowd",
          tableBodySubTitle: "SMRTCRWD",
          tableBodyPrice: "2.56",
          tableBodyChanee: "+13.65",
        },
        {
          tableId: "1b",
          tableBodyTitle: "GetStake",
          tableBodySubTitle: "GSTKD",
          tableBodyPrice: "19.43",
          tableBodyChanee: "+11.19",
        },
        {
          tableId: "1c",
          tableBodyTitle: "Aqarchain",
          tableBodySubTitle: "AQAR",
          tableBodyPrice: "8.93",
          tableBodyChanee: "-6.955",
        },
      ],
    },
    {
      card: "two",
      title: "Virtual Digital Assets",
      bgColor: "#ffefbd",
      name: "Metaverse, Web3 & Gaming Platforms",
      subName: "Recent Transactions",
      tableTitleOne: "Name",
      tableTitleTwo: "Price",
      tableTitleThree: "Chanee",
      tableData: [
        {
          tableId: "1d",
          tableBodyTitle: "SmartCrowd",
          tableBodySubTitle: "SMRTCRWD",
          tableBodyPrice: "2.56",
          tableBodyChanee: "+13.65",
        },
        {
          tableId: "1e",
          tableBodyTitle: "GetStake",
          tableBodySubTitle: "GSTKD",
          tableBodyPrice: "19.43",
          tableBodyChanee: "+11.19",
        },
        {
          tableId: "1f",
          tableBodyTitle: "Aqarchain",
          tableBodySubTitle: "AQAR",
          tableBodyPrice: "8.93",
          tableBodyChanee: "-6.955",
        },
      ],
    },
    {
      card: "three",
      title: "Phyrtual-Hybrid Assets",
      name: "Physical to Digital Link",
      subName: "Recent Transactions",
      tableTitleOne: "Name",
      tableTitleTwo: "Price",
      tableTitleThree: "Chanee",
      tableData: [
        {
          tableId: "1g",
          tableBodyTitle: "SmartCrowd",
          tableBodySubTitle: "SMRTCRWD",
          tableBodyPrice: "2.56",
          tableBodyChanee: "+13.65",
        },
        {
          tableId: "1h",
          tableBodyTitle: "GetStake",
          tableBodySubTitle: "GSTKD",
          tableBodyPrice: "19.43",
          tableBodyChanee: "+11.19",
        },
        {
          tableId: "1i",
          tableBodyTitle: "Aqarchain",
          tableBodySubTitle: "AQAR",
          tableBodyPrice: "8.93",
          tableBodyChanee: "-6.955",
        },
      ],
    },
];

export const leaderboardsTableData = [
    {
      title: "Virtual Land & Real Estate/NFTS (BsMetaverse/Web3/Gaming)",
      bgColor: "#8ff129",
      color: "black",
      data: [
        {
          id: 1,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 2,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 3,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 4,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 5,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
      ],
    },
    {
      title: "Crowdfunding Market",
      bgColor: "#8ff129",
      color: "black",
      data: [
        {
          id: 1,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 2,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 3,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 4,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
      ],
    },
    {
      title: "Phyrtual-Hybrid Market",
      bgColor: "#8ff129",
      color: "black",
      data: [
        {
          id: 1,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 2,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 3,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
        {
          id: 4,
          icon: "BsMeta",
          iconName: "Arra",
          iconSubTitle: "+2.54%",
          marketCap: "446,517,68",
          floor: "243",
          "1D vol": 7266,
          "1D%": "-55.2%",
          "7D Vol": "972.9%",
          "7D%": "-52.61",
          owners: "7.1k",
        },
      ],
    },
];
  
export const dashboardYourAssets = [
    {
      num: "one",
      title: "1.25 BTC",
      subTitle: "$2,4506",
      description: "Physical Real Estate",
      subDes: "+0.34%",
    },
    {
      num: "two",
      title: "0.32 LTC",
      subTitle: "$2,4506",
      description: "Metaverse Lands",
      subDes: "+0.34%",
    },
    {
      num: "three",
      title: "1.25 ETH",
      subTitle: "$2,4506",
      description: "Digital Assets",
      subDes: "+0.34%",
    },
    {
      num: "four",
      title: "6.73 BTC",
      subTitle: "$5,121.17",
      description: "Other Assets",
      subDes: "+0.34%",
    },
  ];
  
export const dashboardPerformanceTable = [
    {
      id: "one",
      icon: "SmartCrowd",
      iconName: "SmartCrowd",
      iconSubTitle: "SMARTCRWD",
      price: "$2.56",
      chanee: "+13.56%",
      marketCap: "$400.8M",
    },
    {
      id: "two",
      icon: "GetStake",
      iconName: "GetStake",
      iconSubTitle: "GSTKD",
      price: "$10.43",
      chanee: "+11.19%",
      marketCap: "$400.8M",
    },
    {
      id: "three",
      icon: "Aqarchain",
      iconName: "Aqarchain",
      iconSubTitle: "AQAR",
      price: "$8.93",
      chanee: "-6.94%",
      marketCap: "$400.8M",
    },
    {
      id: "four",
      icon: "BsMeta",
      iconName: "Meta",
      iconSubTitle: "META",
      price: "$2.56",
      chanee: "-2.45%",
      marketCap: "$400.8M",
    },
    {
      id: "five",
      icon: "VelChain",
      iconName: "VelChain",
      iconSubTitle: "VET",
      price: "$112.14",
      chanee: "+6.80%",
      marketCap: "$400.8M",
    },
    {
      id: "six",
      icon: "AAVE",
      iconName: "AaVe",
      iconSubTitle: "AAVE",
      price: "$32.18",
      chanee: "+3.76%",
      marketCap: "$400.8M",
    },
  ];
  
export const dashboardInviteData = [
    {
      title: "Get $10 in free real estate",
      subTitle: "Give a friend the gift of free real estate",
      description:
        "Invite a friend to araa & you'll both receive in free real estate assets when they buy or sell their first $100 on",
    //   img: InviteImg,
      subDes: "Only certain users can accept your invitation",
      terms: "View Terms & Conditions",
    },
  ];
  
export const communityStoriesData = [
    {
      id: 6,
      name: "Your Story",
    //   img: Daniel,
    },
    {
      id: 7,
      name: "Cody Fisher",
    //   img: Cody,
    },
    {
      id: 8,
      name: "Your Story",
    //   img: Daniel,
    },
    {
      id: 9,
      name: "Cody Fisher",
    //   img: Cody,
    },
    {
      id: 10,
      name: "Your Story",
    //   img: Daniel,
    },
    {
      id: 11,
      name: "Cody Fisher",
    //   img: Cody,
    },
    {
      id: 12,
      name: "Your Story",
    //   img: Daniel,
    },
    {
      id: 13,
      name: "Cody Fisher",
    //   img: Cody,
    },
    {
      id: 14,
      name: "Your Story",
    //   img: Daniel,
    },
    {
      id: 15,
      name: "Cody Fisher",
    //   img: Cody,
    },
  ];
  
export const communityDanielAccordian = [
    {
      name: "Daniel Saliba",
    //   img: Daniel,
    //   carouselImg: CarouselImg,
      location: "Dubai UAE",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat null pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
  ];
  
export const communityDanielInfo = [
    {
      name: "Daniel Saliba",
    //   img: Daniel,
      mail: "@danielsaliba",
      location: "Dubai UAE",
      posts: "2.6k",
      following: 1050,
      followers: 2400,
    },
  ];
  
export const communityTrendingData = [
    {
      title: "Trending News",
      btn: "View All",
    //   img: StockMarketArrow,
      titleOne: "Crypto Big Losses...",
      titleTwo: "Bitcoin Make S&P No. 1",
      titleThree: "#Crypto",
      descOne: "Read More",
      descTwo: "Read More",
      descThree: "Ethereum",
    },
    {
      title: "Trending Groups",
      btn: "View All",
    //   img: StockMarketArrow,
      titleOne: "#AraaRealEstate",
      titleTwo: "#Games",
      titleThree: "#Crypto",
      descOne: "1040 Posts",
      descTwo: "547 Posts",
      descThree: "Ethereum",
    },
  ];